### ISSUE TITLE
Method 2 is sent 

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#268] opened 2016-09-26 08:50 UTC
Method 2 is called even though the file to enable this does not exist. @Boxedsolutions knows how to fix this now.

Push hotfix as soon as it is tested by @kalorifri.

**Comment by Boxedsolutions** [comment] 2016-09-26 08:56
Should be fixed in 195501d

**Comment by kalorifri** [comment] 2016-09-28 08:52
Tested and confirmed the issue is fixed.

**Comment by kalorifri** [comment] 2016-10-20 08:09
Fixed in release 2.1.7

**Closed by kalorifri** 2016-10-20 08:09 UTC
Labels: bug
