### ISSUE TITLE
Add compatibility with "One page checkout for Prestashop Module"

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/prestashop#108] opened 2015-02-19 20:31 UTC
Also add support for get adress.

http://addons.prestashop.com/en/checkout-modules/6841-one-page-checkout-for-prestashop.html

**Comment by Boxedsolutions** [comment] 2015-09-11 07:01
Duplicate of #105

**Comment by HansFrolich** [comment] 2016-03-21 13:06
Which module / 3rd party product is "One Page Checkout" and Billmate compatible with? One documentation and how it works? Any recommendation? Thanks!

**Comment by Boxedsolutions** [comment] 2016-03-21 13:55
It should be the one linked here http://addons.prestashop.com/en/checkout-modules/6841-one-page-checkout-for-prestashop.html

**Comment by Boxedsolutions** [comment] 2016-03-29 06:29
Should be fixed

**Comment by victorauren** [comment] 2016-03-31 14:13
It doesn't appear in checkout.

**Comment by Boxedsolutions** [comment] 2016-04-04 12:07
If it works at our Victor test it should be fixed

**Comment by victorauren** [comment] 2016-04-04 13:43
Works fine. Tested severel times. But what about the button to click? Should we do something about it?

**Comment by Boxedsolutions** [comment] 2016-04-05 07:54
Think we cant solve the click issue.

**Comment by victorauren** [comment] 2016-04-05 09:53
Seems to be a OPC issue
Should we leave it for now?

**Comment by Boxedsolutions** [comment] 2016-04-05 10:41
@victorauren Think we leave it now.

**Comment by victorauren** [comment] 2016-04-06 06:36
Closing issue, the 2 click issue is in another ticket

**Closed by victorauren** 2016-04-06 06:36 UTC
Labels: duplicate, enhancement
